// Generated by CoffeeScript 1.10.0
var join, walk;

walk = require("walk").walk;

join = require("path").join;

module.exports = function(dir) {
  var promise;
  promise = new Promise(function(resolve, reject) {
    var map, walker;
    walker = walk(dir);
    map = {};
    walker.on("file", function(root, file, next) {
      var info, ref;
      info = file.name.split(".");
      if ((ref = info[1]) !== "coffee" && ref !== "styl" && ref !== "jade") {
        map["/" + info[0]] = join(root, file.name);
      }
      return next();
    });
    return walker.on("end", function() {
      return resolve(map);
    });
  });
  return promise;
};
