// Generated by CoffeeScript 1.10.0
var app, bodyParser, express, join, p, port, ref, serveApp;

join = require("path").join;

express = require("express");

bodyParser = require("body-parser");

serveApp = require("./serveApp");

port = (ref = process.env.PORT) != null ? ref : 3000;

app = express();

app.use(bodyParser.json());

p = join(__dirname, "../client");

console.log(p);

app.use(serveApp(p));

app.listen(port, function() {
  return console.log("Server started at port : " + port);
});
