// Generated by CoffeeScript 1.10.0
var mapDir;

mapDir = require("./mapDir");

module.exports = function(app) {
  return function(req, res, next) {
    var map;
    map = mapDir(app);
    return map.then(function(m) {
      var url;
      url = req.url;
      if (req.method === "GET" && (m[url] != null)) {
        res.sendFile(m[url]);
        return;
      } else if (url === "/") {
        res.sendFile(m["/index"]);
        return;
      }
      return res.sendFile(m["/error"]);
    });
  };
};
