// Generated by CoffeeScript 1.10.0
var fs, join, map, walk, walker;

walk = require("walk").walk;

join = require("path").join;

fs = require("fs");

walker = walk(join(__dirname, "../client"));

map = {};

walker.on("file", function(root, file, next) {
  var info, path, ref;
  info = file.name.split(".");
  if (info[1] === "html" && ((ref = info[0]) !== "index" && ref !== "error")) {
    path = join(root, file.name);
    map[info[0]] = fs.readFileSync(path, "utf8");
  }
  return next();
});

walker.on("end", function() {
  var file;
  file = join(__dirname, "template.coffee");
  return fs.writeFileSync(file, "map = " + (JSON.stringify(map)) + "\nmodule.exports = (tmp) -> map[tmp]");
});
