// Generated by CoffeeScript 1.10.0
module.exports = function($scope) {
  var lock, picture;
  this.$inject = ["$scope"];
  $scope.x = 9;
  $scope.y = 9;
  picture = [];
  lock = 0;
  $scope.run = function(x, y) {
    var i, j, k, len, ref, results;
    $scope.x = x;
    $scope.y = y;
    $scope.start = true;
    picture = new Array(x);
    ref = $scope.range(x);
    results = [];
    for (k = 0, len = ref.length; k < len; k++) {
      i = ref[k];
      picture[i] = new Array(y);
      results.push((function() {
        var l, len1, ref1, results1;
        ref1 = $scope.range(y);
        results1 = [];
        for (l = 0, len1 = ref1.length; l < len1; l++) {
          j = ref1[l];
          results1.push(picture[i][j] = 0);
        }
        return results1;
      })());
    }
    return results;
  };
  $scope.range = function(r) {
    var k, ref, results;
    return (function() {
      results = [];
      for (var k = 0, ref = r - 1; 0 <= ref ? k <= ref : k >= ref; 0 <= ref ? k++ : k--){ results.push(k); }
      return results;
    }).apply(this);
  };
  $scope["class"] = function(i, j) {
    switch (picture[i][j]) {
      case 1:
        return "red-untouched";
      case 2:
        return "red-touched";
      case 3:
        return "blue-untouched";
      case 4:
        return "blue-touched";
      case 5:
        return "green-untouched";
      case 6:
        return "green-touched";
      default:
        return "default";
    }
  };
  $scope.draw = function(x, y) {
    if (lock) {
      return;
    }
    if (picture[x][y] === 3) {
      return picture[x][y] = 0;
    } else {
      return picture[x][y] = 3;
    }
  };
  $scope.go = function() {
    var x, y;
    lock = 1;
    x = y = 0;
    return setInterval(function() {
      picture[x][y] = 1;
      return $scope.$digest();
    }, 5000);
  };
  return $scope;
};
