// Generated by CoffeeScript 1.10.0
require("safe-angular");

require("safe-angular-animate");

require("safe-angular-aria");

require("safe-angular-messages");

require("safe-angular-material");

module.exports = {
  "angular": angular,
  "angular-animate": "ngAnimate",
  "angular-aria": "ngAria",
  "angular-messages": "ngMessages",
  "angular-material": "ngMaterial"
};
