// Generated by CoffeeScript 1.10.0
var angular, dependencies, deps, moduleName;

dependencies = require("./dependencies");

angular = dependencies.angular;

moduleName = "main";

deps = [dependencies["angular-animate"], dependencies["angular-aria"], dependencies["angular-messages"], dependencies["angular-material"]];

angular.module(moduleName, deps).controller("main", require("./controller"));

angular.element(document).ready(function() {
  return angular.bootstrap(document, [moduleName]);
});
